### ISSUE TITLE
Page build failure when used with remote theme

### ISSUE THREAD

**Issue by acjh13** [MihajloNesic/jekyll-pdf-embed#1]
Hi there, first off thanks for making this gem!

I'm pretty new to jekyll in general and this gem was exactly what I needed for embedding pdfs.

It worked fine locally but I got this error when I committed it onto Github.

> The page build failed for the `master` branch with the following error:
>The tag `pdf` on line 1 in `_pages/resume.md` is not a recognized Liquid tag

Any idea what's causing this?

**Comment by MihajloNesic** [comment]
The problem is GitHub Pages because:

> GitHub Pages cannot build sites using unsupported plugins. If you want to use unsupported plugins, generate your site locally and then push your site's static files to GitHub Enterprise.

These are the gems/plugins allowed 
https://pages.github.com/versions/ and https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins

That's a bummer :/

For the time being, you can try to migrate to GitLab! My Jekyll website is hosted there and I haven't had any issues with it. And it is really easy to setup!

Here are some links:
[1] https://stackoverflow.com/questions/54499478/my-liquid-tag-is-not-recognized-by-github-pages/54501512#54501512
[2] https://stackoverflow.com/questions/20830997/failed-to-build-page-jekyllgallerytag/20848226#20848226
[3] https://docs.github.com/en/enterprise/2.17/user/github/working-with-github-pages/about-github-pages-and-jekyll

**Comment by acjh13** [comment]
Ah I see, that's disappointing. I'll certainly consider migrating to GitLab in the future.

Thanks for taking the time to clarify this for me, closing the issue!
